
name: Clean Artifacts

on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      actions:  write

    steps:
    - name: 清理 workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 4

    - name: 清理 releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 4
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

